### ISSUE TITLE
Getting Range actions are not supported.

### ISSUE THREAD

**Issue by milos12345** [MintPlayer/MintPlayer.Dotnet.Tools#2]
I tried this in my project with WPF and .NET 4.8 (I already had some simple implementation of RangeObservableCollection). I added Nuget package and removed `using System.Collections.ObjectModel; `and replaced it with `using MintPlayer.ObservableCollection;`
On first 
`this.FilesCollection.AddRange(templist);`

I get

> Range actions are not supported.
>    at System.Windows.Data.ListCollectionView.ValidateCollectionChangedEventArgs(NotifyCollectionChangedEventArgs e)
>    at System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
>    at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
>    at MintPlayer.ObservableCollection.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
>    at MyNamespace.FilesListBox.<>c__DisplayClass58_0.<OutputFiles>b__0() in D:\tempRapid\MyNamespace\MyNamespace\V3\FilesListBox.cs:line 1479
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.DispatcherOperation.InvokeImpl()
>    at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Windows.Threading.DispatcherOperation.Invoke()
>    at System.Windows.Threading.Dispatcher.ProcessQueue()
>    at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
>    at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
>    at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
>    at System.Windows.Application.RunDispatcher(Object ignore)
>    at System.Windows.Application.RunInternal(Window window)
>    at MyNamespace.App.Main()

**Comment by PieterjanDeClippel** [comment]
Bumped into the same case a week ago. It appears that WPF cannot deal with range operations. I just did some tests:

- **WPF (.NET Framework):** not supported
- **WPF (.NET Core):** not supported
- **Xamarin.Forms:** supported

**Comment by PieterjanDeClippel** [comment]
Here is a working demo: https://github.com/PieterjanDeClippel/WpfObservableRangeCollectionPOC

Implementation of [following gist](https://gist.github.com/weitzhandler/65ac9113e31d12e697cb58cd92601091)

I will try to implement this in the future.

**Comment by PieterjanDeClippel** [comment]
Fixed in https://www.nuget.org/packages/MintPlayer.ObservableCollection/1.0.4

Here is [a working sample](https://github.com/PieterjanDeClippel/WpfRangeOperations)
