### ISSUE TITLE
Bug when using the AddRange/RemoveRange methods when the collection contains no items

### ISSUE THREAD

**Issue by rubend30** [MintPlayer/MintPlayer.Dotnet.Tools#4]
Hello

When using the `AddRange` or `RemoveRange ` methods an Exception (`Range actions are not supported.`) is thrown when the collection trying to add/remove is empty.
It is a simple check in my code to check if the collection contains items but it may be better to handle this in the `ObservableCollection` class?

You can test this by trying to add or remove an empty collection to the `ObservableCollection` instance.

**Comment by PieterjanDeClippel** [comment]
Hi,

Thanks for reporting the issue. However, [I created a simple test case](https://github.com/MintPlayer/MintPlayer.ObservableCollection/commit/dfbd60d9fb88dae4cc39a60ea2b9ec7150002963) (yes I should be starting to use unit-testing/integration-testing here) and I'm currently unable to reproduce the issue that you're experiencing. I've run the test case on .NET Core 3.0 and 3.1.

It is my opinion that libraries used in applications should work as expected, so I'm curious to pinpoint the issue that you're experiencing.

Would it perhaps be possible to either
- Share your code
- If for commercial reasons - Reduce your code up to a point where you could share it and the issue still occurs
- Create a minimal reproduction of the code

Glad to receive your feedback,
Yours sincerely
Pieterjan

**Comment by rubend30** [comment]
Hello

I probably did not explain the issue good enough. It happens when the parameter used in the `AddRange ` or `RemoveRange `method is an empty list/collection. I have added a sample application (.zip file with project), I have run against .NET 5.0, .NET Core 3.0 and 3.1 and it is always the same issue.

I used the application you provided but commented the items inside the collection so that the parameters is an empty list.
[WpfRangeOperations.zip](https://github.com/MintPlayer/MintPlayer.ObservableCollection/files/6726287/WpfRangeOperations.zip)

Thank you for the reply and time.

**Comment by PieterjanDeClippel** [comment]
Hi,

I've implemented a fix for your issue in version 1.4.0 ([Commit reference](https://github.com/MintPlayer/MintPlayer.ObservableCollection/commit/34504a69fae999dc2ec23cce8fbccde5038f3173))

**Comment by rubend30** [comment]
Hello

Seems to be fixed.
Now I can remove all my `if(items.Count > 0)` checks ;)

Thank you!

**Comment by PieterjanDeClippel** [comment]
However I see an issue when replacing items in the collection. A fix to both should be relatively easy to implement.

**Comment by PieterjanDeClippel** [comment]
Oh never mind it was the IndexOutOfRangeException caused by commenting out the initial items in the `itemsToAdd`.
